apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-web
  namespace: tiny-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tiny-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tiny-web
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
